name: gambas-hello-world
version: "0.0.1"
summary: Gambas hello world example
description: Gambas hello world example
grade: stable
confinement: devmode

apps:
  vulgry:
    command: desktop-launch $SNAP/bin/vulgry.gambas
    plugs: [unity7, x11, network, network-bind, home, gsettings]

parts:
  vulgry:
    source: https://github.com/johangm90/gambas-hellow-world.git
    plugin: autotools
    install-via: prefix
    build-packages:
      - gambas3-dev
      - gambas3-gb-form
      - gambas3-gb-gui
      - gambas3-gb-image
    stage-packages:
      - gambas3-runtime
      - gambas3-gb-form
      - gambas3-gb-gui
      - gambas3-gb-image
    after: [desktop-gtk3]
